### ISSUE TITLE
Google Play and Evolve

### ISSUE THREAD

**Issue by MarkySmarky** [VivekPanyam/Evolve#1]
Hey man,
How does Google detect that an app is trying to download and run code remotely? Is it an automatic process done by Google? For example, if I use this library but don't ever download new code - so that it's not really used - will it come up on their radar somehow?
Thanks

**Comment by VivekPanyam** [comment]
Honestly, I'm not sure. I don't think there is an automated check right now, but if it becomes a problem, I think Google will add one. It might make sense to have another library that has empty implementations of `DynamicActivity`, `DynamicListActivity`, and `Evolve`. This way you can just switch out the actual Evolve library with this one before pushing to Google Play.
