### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by andersonchagas** [VivekPanyam/Evolve#11]
Hi, 

If is possible, I need more help to use this solution.

There is some kind of tutorial?

I dont know how can I include Evolve in my app?

I'm using Android Studio.

**Comment by VivekPanyam** [comment]
Have you looked at the [Using Evolve](https://github.com/VivekPanyam/Evolve#using-evolve) section of the readme?

There's also a [blog post introducing the project](https://blog.vivekpanyam.com/evolve-seamlessly-deploy-android-apps-to-users/). (There's a lot of overlap between this post and the readme).

There isn't a formal tutorial, but feel free to add a comment to this issue if you have any specific questions.

There is a prebuilt version of the library here: https://github.com/VivekPanyam/Evolve/releases

If you're using Gradle, here's a link that might help with including a library: http://stackoverflow.com/questions/16608135/android-studio-add-jar-as-library
