### ISSUE TITLE
Using AlertDialog.Builder from an inner app

### ISSUE THREAD

**Issue by ravanova** [VivekPanyam/Evolve#7]
I don't seem to be able to use AlertDialog.Builder from within the dynamically loaded application.
When I do I get the error:

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>

This makes me think that it is to do with AlertDialog.builder not being Dynamic.
Is this something which has been encountered before?

**Comment by ravanova** [comment]
It appears to be an issue with context. Is there an easy way to get the context of the wrapper application from within the dynamically loaded apk?

**Comment by VivekPanyam** [comment]
`Evolve.context` will contain a context from the wrapper app
