### ISSUE TITLE
Using an IntentService within the dynamically loaded application

### ISSUE THREAD

**Issue by ravanova** [VivekPanyam/Evolve#9]
I am trying to run a class which extends IntentService from within the inner application.
It is failing to launch; have any of you managed to successfully get IntentService classes to work in this way with Evolve?

Thanks in advance :)

**Comment by VivekPanyam** [comment]
I haven't implemented support for services in Evolve. However, it appears that the same general idea could work for IntentServices. Declare generic dummy services in the wrapper manifest and implement them in the main application. Let me know if you have any questions!
